# Gamello Local User Microservice Configuration
# intended use: running on local machine
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/app_user
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: create-drop
    cache:
        type: redis
        redis:
            time-to-live: 3600
    redis:
        host: 127.0.0.1
        port: 6379
aws:
    access: AKIARYQQ3CL4AK5IW57G
    secret: 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
    regions:
        s3: eu-central-1
confirmation:
    email:
        service-url: "http://mailer.gamello:8080/transactional"
        enabled: false
avatar:
    bucket-name: gamello-upload-dev
    avatars-location: test/images/avatars/
    default-avatar-location: app/images/default_avatar/default_avatar