# Gamello Local User Microservice Configuration
# intended use: running on local machine
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/app_user
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: create-drop
    cache:
        type: simple
        redis:
            time-to-live: 3600
    redis:
        host: 127.0.0.1
        port: 6379
aws:
    access:
    secret:
    regions:
        s3:
confirmation:
    email:
        service-url:
        enabled: false
avatar:
    bucket-name: gamello-upload-dev
    avatars-location: test/images/avatars/
    default-avatar-location: app/images/default_avatar/default_avatar