# Gamello Development User Microservice Configuration
# intended use: running on Gamello main development cluster
spring:
    datasource:
        url:
        username:
        password:
    jpa:
        hibernate:
            ddl-auto: update
    cache:
        type: redis
        redis:
            time-to-live: 3600
    redis:
        host:
        port:
aws:
    access:
    secret:
    regions:
        s3:
confirmation:
    email:
        service-url:
avatar:
    bucket-name: gamello-upload-dev
    avatars-location: test/images/avatars/
    default-avatar-location: app/images/default_avatar/default_avatar