spring:
    application:
        name: user
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
token:
    chars-length: 18
    number-of-sections: 4